Not existing tokens should return 200 as well withing introspection
jazzband/django-oauth-toolkit pull request #1012
Opened 2021-09-15 07:57 UTC by ZuSe

Compare with https://datatracker.ietf.org/doc/html/rfc7662

Fixes #

## Description of the Change

## Checklist

- [ X] PR only contains one change (considered splitting up PR)
- [ X] unit-test added
- [ X] documentation updated
- [ X] `CHANGELOG.md` updated (only for user relevant changes)
- [X ] author name in `AUTHORS`

2021-09-21 12:53 UTC, auvipy approved these changes

2021-09-21 12:59 UTC, auvipy submitted a review, later dismissed
you need to update the tests as well

2021-12-22 16:23 UTC, n2ygk requested changes
Thanks for this. It looks right but needs the tests fixed. Also, you indicated that CHANGELOG was updated, AUTHORS, etc. but I don't see where you've done that.

The tests looks pretty easy to fix: 
```
  E       AssertionError: 200 != 401
```

Please let me know if you can get to this soon as I'm targeting this for the next minor release.

2022-01-01 17:08 UTC, n2ygk commented
I've updated the checklist to indicate correct status of this PR.

2022-01-01 17:32 UTC, n2ygk approved these changes

2022-01-01 17:41 UTC, merged