Enhance clear_expired tests.
jazzband/django-oauth-toolkit pull request #1088
Opened 2022-01-11 21:55 UTC by n2ygk

Fixes #1065

## Description of the Change

* Flags no coverage for cleartoken management command since the test is in test_models.
* Expand coverage of the clear_expired tests.

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [x] unit-test added
- [ ] documentation updated
- [ ] `CHANGELOG.md` updated (only for user relevant changes)
- [x] author name in `AUTHORS`

2022-01-11 22:02 UTC, n2ygk commented
@Andrew-Chen-Wang See 6ddb3d7 for broken commit due to: `ValueError: bulk_create() prohibited to prevent data loss due to unsaved related object 'access_token'.` in attempting to follow your advice at https://github.com/jazzband/django-oauth-toolkit/pull/1084#discussion_r781647956

2022-01-12 01:13 UTC, Andrew-Chen-Wang requested changes
f-strings used for performance and readability improvement.

`bulk_create` does not call `save()`, but the pks are set given the database is Postgres, MariaDB, or SQLite3 (at some version+ that GitHub actions and all modern computers prob already have).

For reference, here's where it's set: https://github.com/django/django/blob/dc9deea8e85641695e489e43ed5d5638134c15c7/django/db/models/query.py#L514

2022-01-12 01:13 UTC, Andrew-Chen-Wang commented on tests/test_models.py
> +                access_token=expired_access_tokens[i],
```suggestion
                access_token_pk=expired_access_tokens[i].pk,
```

2022-01-12 01:13 UTC, Andrew-Chen-Wang commented on tests/test_models.py
> +                token="expired AT's refresh token {}".format(i),
```suggestion
                token=f"expired AT's refresh token {i}",
```

2022-01-12 01:13 UTC, Andrew-Chen-Wang commented on tests/test_models.py
> +            AccessToken(token="current AccessToken {}".format(i), expires=later) for i in range(100)
```suggestion
            AccessToken(token=f"current AccessToken {i}", expires=later) for i in range(100)
```

2022-01-12 01:13 UTC, Andrew-Chen-Wang commented on tests/test_models.py
> +                token="current AT's refresh token {}".format(i),
```suggestion
                token=f"current AT's refresh token {i}",
```

2022-01-12 01:13 UTC, Andrew-Chen-Wang commented on tests/test_models.py
> +                access_token=expired_access_tokens[i],
```suggestion
                access_token_pk=expired_access_tokens[i].pk,
```

2022-01-12 01:13 UTC, Andrew-Chen-Wang commented on tests/test_models.py
> +                code="old grant code {}".format(i),
```suggestion
                code=f"old grant code {i}",
```

2022-01-12 01:13 UTC, Andrew-Chen-Wang commented on tests/test_models.py
> +                expires=expired_access_tokens[i],
I don't think you can set the access token to this DateTimeField if I'm not mistaken.
```suggestion
                expires=expired_access_tokens[i].expires,
```

2022-01-12 01:13 UTC, Andrew-Chen-Wang commented on tests/test_models.py
> +                code="new grant code {}".format(i),
```suggestion
                code=f"new grant code {i}",
```

2022-01-12 01:13 UTC, Andrew-Chen-Wang commented on tests/test_models.py
> +                expires=current_access_tokens[i],
I don't think you can set the access token to this DateTimeField if I'm not mistaken.
```suggestion
                expires=current_access_tokens[i].expires,
```

2022-01-12 18:34 UTC, n2ygk commented
I'll circle back soon and make sure my test logic is correct (probably isn't) now that the code is running;-)

2022-01-12 22:58 UTC, Andrew-Chen-Wang approved these changes
LGTM!

2022-01-12 23:53 UTC, merged