feat: Update PKCE_REQUIRED to true by default
jazzband/django-oauth-toolkit pull request #1129
Opened 2022-03-21 14:46 UTC by dopry

Assuming PKCE is properly implemented this change should be backwards
compatible with clients that do not support PKCE, see:
https://datatracker.ietf.org/doc/html/rfc7636#section-5

Fixes #

## Description of the Change

## Checklist

- [X ] PR only contains one change (considered splitting up PR)
- [ ] unit-test added
- [ X] documentation updated
- [ ] `CHANGELOG.md` updated (only for user relevant changes)
- [X] author name in `AUTHORS`

2022-03-21 14:57 UTC, dopry commented
This is a draft. After reviewing the [compatibility section of RFC7636 Proof Key for Code Exchange by OAuth Public Clients](https://datatracker.ietf.org/doc/html/rfc7636#section-5). It should be backward compatible, so maybe it would be preferable to remove the PKCE setting from userspace and just set it to true in all cases.

2022-03-21 16:41 UTC, dopry commented
> This is a draft. After reviewing the [compatibility section of RFC7636 Proof Key for Code Exchange by OAuth Public Clients](https://datatracker.ietf.org/doc/html/rfc7636#section-5). It should be backward compatible, so maybe it would be preferable to remove the PKCE setting from userspace and just set it to true in all cases.

I actually looked at OAuthLib and it looks like this is a flag to require PKCE in a way that isn't officially specification compliant (it lacks backward compatibility).  The questions that remains in my mind are   

1. is the breaking change worth it or should I  just update the documentation to better inform users, maybe add some sort of 'Warning' for users who don't set this to true.
2. If we pursue the  breaking change, should we follow a deprecation cycle like Django and introduce a deprecation warning for a release?

2022-03-25 17:15 UTC, n2ygk commented
@dopry Have you run the tox tests locally to see that breaks them? I usually start testing with just a single py and dj version:
```
tox -e py39-dj32
```
That still takes a while but then you can focus on the specific tests that fail and run them in your IDE if necessary to determine what happened. I'm guessing most of the failures are because the test case does not use PKCE.

Regarding it being a breaking change: That's OK for release 2.0 which will have many breaking changes. I don't think it's necessary to put this through a deprecation cycle.

2022-03-25 17:18 UTC, n2ygk commented
BTW, If you change the test cases to use PKCE, also make a few failing tests where it's required as well as override the setting to have some successful tests where PKCE_REQUIRED=False.

It looks like test_scopes is the only set of tests that fail.
```
tests/test_scopes.py FFFFFFFF.FF.
```

2022-03-27 15:46 UTC, dopry commented
@n2ygk I wasn't asking about the testing. That's easy.  My question is about how to handle the breaking change of defaulting PKCE_REQUIRED to true. Do we need a deprecation cycle, or is it cool to make the change and just document it.

2022-03-27 16:38 UTC, n2ygk commented
> @n2ygk I wasn't asking about the testing. That's easy.  My question is about how to handle the breaking change of defaulting PKCE_REQUIRED to true. Do we need a deprecation cycle, or is it cool to make the change and just document it. 
> 
> 

Read all the way to the bottom where I said:

Regarding it being a breaking change: That's OK for release 2.0 which will have many breaking changes. I don't think it's necessary to put this through a deprecation cycle.

2022-03-28 20:48 UTC, dopry commented
@n2ygk I missed that paragraph. I believe this should be ready to merge now. I'm assuming that PKCE_REQUIRED as a feature is already well covered by the existing suite of tests. I did add a test to verify that the default value is True.  

Let me know if there is anything you think I missed. 

side note: the test_models is failing for me locally, token clearing doesn't seem to be working properly in my local environment.

2022-03-29 14:23 UTC, n2ygk requested changes
Looks good. Just a minor change to CHANGELOG.md please

2022-03-29 16:53 UTC, n2ygk approved these changes

2022-03-29 17:12 UTC, merged

2022-05-03 18:01 UTC, dopry commented on CHANGELOG.md
> +  in favor of the [OAuth2 Security Best Practices for Authorization Code Grants](`Authorization Code Grant <https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics#section-2.1.>`_ )
Thanks!