Update `createapplication` command
jazzband/django-oauth-toolkit pull request #1132
Opened 2022-03-26 05:50 UTC by vector-kerr

Fixes #
N/A

## Description of the Change

Greetings!

This pull request updates the createapplication management command.

* The `--algorighm` parameter is added which allows specification of `""`, `"RS256"`, or `"HS256"`
* The `--skip-authorization` help text is fixed
    * It was previously incorrectly described as `"The ID of the new application"`
    * It is now described as `"If set, completely bypass the authorization form, even on the first use of the application"`

Notes:
* Documentation not updated because:
    * the command does not appear to be included in documentation
    * the command is self-documented (arguments and help strings displayed on invocation)

I hope you find this change useful!
\- Daniel.

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [x] unit-test added
- [ ] documentation updated
- [x] `CHANGELOG.md` updated (only for user relevant changes)
- [x] author name in `AUTHORS`

2022-03-26 13:48 UTC, n2ygk requested changes
Hey, thanks for this!

Would you consider adding something to the [docs](https://github.com/jazzband/django-oauth-toolkit/blob/master/docs/management_commands.rst) for this command? It's never a bad thing to improve the documentation.

2022-03-26 13:48 UTC, n2ygk commented on CHANGELOG.md
> +* Added `--algorithm` argument to `createapplication` management command
```suggestion
* #1132: Added `--algorithm` argument to `createapplication` management command
```

2022-03-26 13:48 UTC, n2ygk commented on CHANGELOG.md
> +* Fixed help text for `--skip-authorization` argument of the `createapplication` management command
```suggestion
* #1132: Fixed help text for `--skip-authorization` argument of the `createapplication` management command
```

2022-03-27 00:47 UTC, vector-kerr commented
@n2ygk Sure thing, I've had a go at it in commit de0db70.

I'm definitely not an expert on RST documentation (much more familiar and comfortable with markdown) but I gave it a shot.

Someone will probably want to read over it to make sure I haven't buggered it up. I checked it in VSCode with an RST plugin and it seems ok, but I can't be certain.

\- Daniel

2022-03-27 11:37 UTC, n2ygk commented
> @n2ygk Sure thing, I've had a go at it in commit [de0db70](https://github.com/jazzband/django-oauth-toolkit/commit/de0db700a3da94b44e5239461ca4eb130b25f662).
> 
> I'm definitely not an expert on RST documentation (much more familiar and comfortable with markdown) but I gave it a shot.

I think most of us prefer markdown.
> 
> Someone will probably want to read over it to make sure I haven't buggered it up. I checked it in VSCode with an RST plugin and it seems ok, but I can't be certain.

To see what your docs edit looks like, you can locally run `tox -e docs` and then open `docs/_build/html/index.html` to see how it looks. You can similarly click on the [Details](https://django-oauth-toolkit--1132.org.readthedocs.build/en/1132/) for this check: `docs/readthedocs.org:django-oauth-toolkit — Read the Docs build succeeded!`

2022-03-27 11:47 UTC, n2ygk commented
Weirdly the docs build failed even though it works locally.... I'll have to dig a bit further on that.

2022-03-27 11:52 UTC, n2ygk commented
> Weirdly the docs build failed even though it works locally.... I'll have to dig a bit further on that.

This project's tox setup doesn't refresh the `.tox` cache properly. After `rm -r .tox/docs` I can reproduce the error.

2022-03-27 12:10 UTC, n2ygk commented
> > Weirdly the docs build failed even though it works locally.... I'll have to dig a bit further on that.
> 
> This project's tox setup doesn't refresh the `.tox` cache properly. After `rm -r .tox/docs` I can reproduce the error.

Unrelated problem: https://github.com/sphinx-doc/sphinx/issues/10291

2022-03-27 12:50 UTC, vector-kerr commented
Hello again @n2ygk,

I've just merged the master branch into my topical which I presume adds the version pin for jinja2.
If there's anything else you need from my end please let me know. :)

\- Daniel

2022-03-27 13:19 UTC, n2ygk commented
> Hello again @n2ygk,
> 
> I've just merged the master branch into my topical which I presume adds the version pin for jinja2. If there's anything else you need from my end please let me know. :)
> 
> - Daniel

Yeah I'll make sure to resync it with master as there are a few PRs in flight right now. Please either accept or reject the documentation suggestion I made w.r.t table vs. output of `manage.py createapplication --help`.

Thanks!

2022-03-27 13:44 UTC, vector-kerr commented
> Please either accept or reject the documentation suggestion I made w.r.t table vs. output of `manage.py createapplication --help`.

Hello again @n2ygk,

Sorry to be a pain, but I don't seem to be able to find the documentation suggestion you're referring to.

GitHub shows me a big red `"1 change requested"` alert in this conversation, but when I click through with the "View changes" button, it just takes me to the review page where there are no unresolved review requests (that I can see). I also cannot see any obvious difference to the `management_commands.rst` documentation file that you might have made in the diff.

I do use GitLab a lot more than GitHub so I may also just not be looking in the right place...

I'm happy to look over it, I just can't seem to get to it!

2022-03-27 15:18 UTC, n2ygk requested changes
Sorry. I keep doing this. I left my suggestion Pending.

2022-03-27 18:19 UTC, n2ygk commented on docs/management_commands.rst
> ++----------------------------+------+-------------------------------------------------------------------------------------------------+
@vector-kerr see above. Apologies for neglecting to complete by review feedback so it showed for me and I ignored that it was pending.

2022-03-27 20:30 UTC, vector-kerr commented
> Sorry. I keep doing this. I left my suggestion Pending.

Not a problem!
Just committed your suggestion, so I think we're good to go.
Can I please get you to run the workflows once more? (I can't do it myself as a first-time contributor.)
Thanks for your patience and help!

\- Daniel

2022-03-28 11:15 UTC, n2ygk commented on docs/management_commands.rst
> +
Ugh, I forgot this is RsT and not markdown so my suggestion using triple-backticks wasn't so helpful....

2022-03-28 11:56 UTC, n2ygk commented on docs/management_commands.rst
> +
I pushed a commit with the required indentation.

2022-03-28 13:34 UTC, n2ygk approved these changes

2022-03-28 13:35 UTC, merged