Add LOGIN_URL settings in getting_started.rst
jazzband/django-oauth-toolkit pull request #1162
Opened 2022-05-18 06:35 UTC by mumin91

Fixes #

## Description of the Change
Added `LOGIN_URL = '/admin/login/'` to the `settings.py` in DOT tutorial for Django REST Framework. Without this, hitting `http://localhost:8000/o/applications/` redirects to URL not found error page.
## Checklist

- [ ] PR only contains one change (considered splitting up PR)
- [ ] unit-test added
- [x] documentation updated
- [ ] `CHANGELOG.md` updated (only for user relevant changes)
- [ ] author name in `AUTHORS`

2022-05-18 11:02 UTC, n2ygk requested changes
Thanks for this. Would you mind helping out a little more and compare getting_started to the tutorial to see if there are any other things missing from getting_started?

Also please add your name to AUTHORS.

2022-05-27 19:21 UTC, n2ygk commented
@mumin91 Will you be able to make the requested changes?

2022-05-27 19:30 UTC, mumin91 commented
> @mumin91 Will you be able to make the requested changes?

Yes, I will. But I need sometime for that.

2023-05-21 00:18 UTC, dopry commented
@mumin91 Do you have any time to wrap up this PR?

2023-11-10 18:22 UTC, dopry approved these changes
This is at least an improvement until we can update the getting started docs more completely.

2023-11-10 20:41 UTC, merged