Support prompt login
jazzband/django-oauth-toolkit pull request #1164
Opened 2022-05-20 00:08 UTC by jesseyay

Fixes #

## Description of the Change

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [x] unit-test added
- [x] documentation updated
- [x] `CHANGELOG.md` updated (only for user relevant changes)
- [x] author name in `AUTHORS`

2022-05-27 19:08 UTC, n2ygk requested changes
Hey thanks! Please see a couple of documentation suggestions.

2022-05-27 19:08 UTC, n2ygk commented on docs/oidc.rst
> +`OIDC Docs <https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest>`_
```suggestion
OIDC's `3.1.2.1 Authentication Request <https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest>`_
```

2022-05-29 23:20 UTC, jesseyay commented
> Hey thanks! Please see a couple of documentation suggestions.

Yep makes sense, thanks for the review :)

2022-06-03 16:44 UTC, n2ygk commented
darn it, I tried to rebase to fix the CHANGELOG conflict...

2022-06-03 16:45 UTC, n2ygk approved these changes

2022-06-03 17:04 UTC, merged