Add configuration of PKCE_REQUIRED for consumer service
jazzband/django-oauth-toolkit pull request #1190
Opened 2022-08-04 14:36 UTC by fdemmer

## Description of the Change

The consumer service at [heroku](http://django-oauth-toolkit.herokuapp.com/consumer/) does not work as described in the tutorial with `PKCE_REQUIRED=True`. Since this is the default since 2.x the tutorial does not work anymore...

PR adds a note about disabling PKCE to the docs.

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [ ] unit-test added
- [x] documentation updated
- [ ] `CHANGELOG.md` updated (only for user relevant changes)
- [ ] author name in `AUTHORS`

2022-08-15 17:32 UTC, Andrew-Chen-Wang requested changes

2022-08-15 17:32 UTC, Andrew-Chen-Wang commented on docs/tutorial/tutorial_01.rst
> +Disable PKCE requirement for compatibility with the `consumer service <http://django-oauth-toolkit.herokuapp.com/consumer/>`_ deployed on Heroku.
Prepend with the condition that this is on Heroku

2022-08-15 17:56 UTC, n2ygk commented
Unfortunately the herokupapp is out of the current project team's control. Perhaps we should remove references to it, substituting use of Postman as the tool for testing.

2022-12-08 20:28 UTC, Alir3z4 commented
@n2ygk 

> Unfortunately the herokupapp is out of the current project team's control. 

That's a good idea.

> Perhaps we should remove references to it, substituting use of Postman as the tool for testing.

Postman is yet another extra step, maybe the consumer app can be deployed to another hosting that provides? or even better **to have it under full control of this organization/team** maybe running the whole thing in browser hosted on repository github pages as done by https://github.com/m-butterfield/django_webassembly (_live demo: https://django-webassembly.mattbutterfield.com/ hint: browser console shows django being initialized_)

2022-12-12 01:30 UTC, dopry commented
@Alir3z4 I don't think it would be a good idea to host it with the jazzband organization. @jezdez seems generally non-responsive requests and does not have the availability to properly support jazzband projects. It wouldn't be prudent to add any additional dependencies that would require his intervention as a roadie. Docker compose may be a better local solution.

2022-12-12 01:40 UTC, Andrew-Chen-Wang commented
+1 on docker compose

2022-12-12 04:10 UTC, dopry commented
Do we have source for the consumer? I'm pretty handy with docker-compose editing.

2022-12-12 09:43 UTC, jezdez commented
> @Alir3z4 I don't think it would be a good idea to host it with the jazzband organization. @jezdez seems generally non-responsive to requests and does not have the availability to properly support jazzband projects.

Surprise!

> It wouldn't be prudent to add any additional dependencies that would require his intervention as a roadie. Docker compose may be a better local solution.

That's fair, I like docker-compose.

2022-12-12 23:41 UTC, dopry commented
@jezdez good to see you around! I'm heartened to see you're finding the time.

2023-11-10 18:12 UTC, dopry commented
closed since we want to remove all mention of the heroku app. I opened https://github.com/jazzband/django-oauth-toolkit/issues/1360 to track the issue.

2023-11-10 18:12 UTC, closed without merging