Update 0004_auto_20200902_2022.py
jazzband/django-oauth-toolkit pull request #1196
Opened 2022-08-14 23:55 UTC by siddique4

Citus Postgres DB doesnt allow adding of new field with constrains on it.  Example Error attached

You can issue each command separately such as ALTER TABLE oauth2_provider_accesstoken ADD COLUMN id_token data_type; ALTER TABLE oauth2_provider_accesstoken ADD CONSTRAINT constraint_name CHECK (check_expression);

Fixes #

## Description of the Change

## Checklist

- [ ] PR only contains one change (considered splitting up PR)
- [ ] unit-test added
- [ ] documentation updated
- [ ] `CHANGELOG.md` updated (only for user relevant changes)
- [ ] author name in `AUTHORS`

2023-11-10 18:30 UTC, dopry requested changes
Citus postgres isn't technically a supported database. That said I don't see a reason not to do our best to support it. 

However we need to document why we're doing this here. Please add comment explaining why, with links to Citus DB documentation that demonstrates what is not supported and the specific error that you get from Citus if this is not done in 2 steps.

2024-05-07 14:14 UTC, n2ygk commented
@abu-siddique-shipsy will you be doing this?

> Citus postgres isn't technically a supported database. That said I don't see a reason not to do our best to support it.
> 
> However we need to document why we're doing this here. Please add comment explaining why, with links to Citus DB documentation that demonstrates what is not supported and the specific error that you get from Citus if this is not done in 2 steps.

2024-05-20 15:22 UTC, n2ygk commented
@abu-siddique-shipsy Have you opened an issue against Citus that shows this error that makes it non-compliant with Django Postgres support? It seems like that's where the appropriate compatibility fix should live given that DOT is not the only place where migrations like 0004 happen.

Also you say "Example Error attached" above but I don't see the attachment.

2024-05-20 15:24 UTC, n2ygk commented
closing as stale. Feel free to reopen with the requested changes.

2024-05-20 15:24 UTC, closed without merging