handle oauthlib errors on create token and revoke token requests
jazzband/django-oauth-toolkit pull request #1210
Opened 2022-10-04 13:30 UTC by AndrejZbin

Fixes #1209

## Description of the Change

## Checklist

- [ ] PR only contains one change (considered splitting up PR)
- [ ] unit-test added
- [ ] documentation updated
- [ ] `CHANGELOG.md` updated (only for user relevant changes)
- [ ] author name in `AUTHORS`

2022-10-04 14:13 UTC, n2ygk requested changes
@AndrejZbin Thanks for this and filling in the PR template.

Please add test case(s) to demonstrate the original bug and the fix.
Code coverage shows that this new code is not exercised by any tests:

https://github.com/jazzband/django-oauth-toolkit/pull/1210/checks?check_run_id=8701284936

2022-10-06 20:11 UTC, n2ygk requested changes

2022-10-10 07:53 UTC, AndrejZbin commented on oauth2_provider/oauth2_backends.py
> +        except OAuth2Error as exc:
So apparently `create_revocation_response` errors are handled by oauthlib and the added try/except block is redundant in this function. But I think it won't hurt to be on "safe" side and still catch errors from oautlib, at least for consistency across functions. I added test cases that cover the the "except" block in both functions even when the exception is handled by oauthlib. However, if this slight redundancy is not desired, I'm happy to remove it and change only `create_token_response` method.

2022-10-10 13:02 UTC, n2ygk commented on oauth2_provider/oauth2_backends.py
> +        except OAuth2Error as exc:
@AndrejZbin I don't think it's necessary to have extra lines of code that will never be used and mock patching the oauthlib response is inappropriate if oauthlib would never return such a response.

2022-10-10 13:13 UTC, AndrejZbin commented on oauth2_provider/oauth2_backends.py
> +        except OAuth2Error as exc:
Fair enough, I reverted changes to `create_revocation_response` function and removed tests with mock patching.

2022-10-10 13:51 UTC, n2ygk approved these changes
Thanks for this!

2022-10-10 13:52 UTC, merged