Replace heroku with postman tutorial
jazzband/django-oauth-toolkit pull request #1251
Opened 2023-02-14 19:46 UTC by marcusl

Fixes #875 

## Description of the Change

Rewrite documentation to use postman and not the defunct Heroku service.

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [N/A ] unit-test added
- [x] documentation updated
- [N/A] `CHANGELOG.md` updated (only for user relevant changes)
- [N/A] author name in `AUTHORS`

2023-02-14 20:10 UTC, n2ygk requested changes
Thanks for this. Please make sure to add your name to AUTHORS as in the checklist as well as this suggested change.

2023-02-14 20:10 UTC, n2ygk commented on docs/tutorial/tutorial_01.rst
> +For this tutorial, we suggest using Postman, where we will be following `this guide https://columbia-it-django-jsonapi-training.readthedocs.io/en/latest/using_oauth2/#get-an-oauth-20-token`.
I'm not sure if this doc should be linked. I'd prefer that this tutorial doc stand on it's own.
```suggestion
For this tutorial, we suggest using Postman.
```

2023-02-15 14:27 UTC, marcusl commented
Done. :)

2023-02-15 14:51 UTC, n2ygk approved these changes
Thanks!

2023-02-15 15:17 UTC, merged