Allow the use of unhashed secrets
jazzband/django-oauth-toolkit pull request #1311
Opened 2023-09-07 19:52 UTC by gardenerik

Fixes #1239 

## Description of the Change

Adds an option to disable client secrets hashing on save. Also allows the use of applications with unhashed secrets in the HTTP API. This makes it possible to verify OIDC JWTs with HS256.

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [x] unit-test added
- [x] documentation updated
- [ ] `CHANGELOG.md` updated (only for user relevant changes)
- [x] author name in `AUTHORS`

2023-09-07 20:02 UTC, n2ygk commented
Please request a review when you are ready....

2023-09-07 20:14 UTC, gardenerik commented
@n2ygk it seems I am unable to request a review through the UI, but feel free to review the PR

2023-09-07 20:15 UTC, n2ygk commented
> @n2ygk it seems I am unable to request a review through the UI, but feel free to review the PR

Looks like you added them (or someone did)

2023-09-07 20:32 UTC, gardenerik commented
I am not sure what you are talking about :( The reviewers section is empty.

2023-09-08 12:55 UTC, n2ygk commented
> I am not sure what you are talking about :( The reviewers section is empty. ![image](https://user-images.githubusercontent.com/11409143/266435242-204805f3-a0d2-41de-b5ef-adec1f6d6a77.png)

Haha I was looking at *my* suggestions:

![image](https://github.com/jazzband/django-oauth-toolkit/assets/4356471/4187a992-9cc7-4125-9273-3873c641c8a4)

2023-09-08 13:35 UTC, n2ygk commented
@Andrew-Chen-Wang I've added you as a reviewer mostly as an FYI.

2023-09-10 20:27 UTC, gardenerik commented
@n2ygk I have updated your points, thanks for the feedback

2023-09-12 13:14 UTC, n2ygk requested changes
Thanks for leaving the campground cleaner than when you found it:-)

I have proposed one minor wording change just to make clear that there's a security exposure to not hashing client secrets.

2023-09-12 13:14 UTC, n2ygk commented on docs/getting_started.rst
> +If you want to use this application with OIDC and ``HS256`` (see :doc:`OpenID Connect <oidc>`), uncheck ``Hash client secret`` to allow verifying tokens using JWT signatures.
```suggestion
If you want to use this application with OIDC and ``HS256`` (see :doc:`OpenID Connect <oidc>`), uncheck ``Hash client secret`` to allow verifying tokens using JWT signatures. This means your client secret will be stored in cleartext but is the only way to successfully use signed JWT's.
```

2023-09-12 20:17 UTC, n2ygk approved these changes

2023-09-12 20:57 UTC, n2ygk commented
Looks like pytest broke probably due to some version issue. Will look at it tomorrow or Thursday

2023-09-13 15:37 UTC, n2ygk commented
Hmm a migrations conflict: 
```
E           django.core.management.base.CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0008_alter_accesstoken_token, 0008_add_hash_client_secret in oauth2_provider).
E           To fix them run 'python manage.py makemigrations --merge'
```

2023-09-13 18:22 UTC, n2ygk commented
My fault. I merged #1312 which created the migration conflict. Fixing it now.

2023-09-13 18:51 UTC, merged

2023-11-24 08:38 UTC, hugochinchilla commented
I know I can install this from git but I think this fix is important enought to create a new release on PyPI.

Thank you for your work :)

2024-04-29 00:31 UTC, relrod commented
@n2ygk (from one ham radio op to another :smiling_face_with_tear:) any chance of a release with this fix in the near-ish future?

2024-05-13 15:02 UTC, n2ygk commented
FYI - as part of the release, I'm strengthening the language to recommend using RS256 keys which is a more secure approach than HS256 and does not require retaining the `client_secret` as cleartext.

2024-08-01 06:40 UTC, blag commented
> This may lead to incompatibilities with some OIDC Relying Party libraries.

Although I think I know the answer, I have a clarification question. Does the "This" in this sentence mean that:

1. The case when the box is checked (and the client secret is hashed) may lead to incompatibilities with some OIDC RP libraries or...
2. The case when the box is unchecked (and the client secret is left unhashed) may lead to incompatibilities with some OIDC RP libraries

?

Because it isn't 100% perfectly clear here to me, and I'm not an expert on OIDC.

Once I get an answer I'll provide a PR to tweak/fix the language.

2024-08-01 09:06 UTC, gardenerik commented
When the box is checked and HS256 is used with OIDC.

HS256 requires that the token is signed by a symmetric key that is shared between the Relying Party and the Authorization Server. The application's secret is used for this signature.

When you leave "hash secret" checked, the Authorization Server will lose the original secret value and will use the hashed secret when signing the token. But this breaks the OIDC's contract as the Relying Party is no longer able to verify the token's signature.

The token is completely valid from the OAuth Toolkit's viewpoint - you can use it to authenticate against Django views, etc.
Good OIDC libraries should check the signature by default, but when doing so, they will reject the provided token, as the signatures mismatch.

You can leave "hash secret" checked without any problems if you:

- use RS256 (the token is signed by `OIDC_RSA_PRIVATE_KEY` and thus verified using the toolkit's public key)
- use HS256, but do not use OIDC, only OAuth2 - OAuth2 does not have any specifications on the token, so it is just treated as a string

2024-08-23 16:55 UTC, blag commented
@gardenerik Thanks for the explanation, that's what I thought. I'll whip up a PR to tweak the help text to be a tiny bit more clear about what state it's referring to.

As a slightly separate issue: when a user unchecks the box and uses HS256 with OIDC, does it make sense to leave the (unhashed) symmetric key visible to the user on future page loads? It seems to me that a lot of secret values are only shown once to the user (this is exactly how GitHub works with developer keys), and I assume that this is done to make it more difficult for an attacker to steal or the secret from the OIDC provider and/or spoof the provider entirely (with the correct shared secret).

When a user chooses to leave the "hash secret" option checked when registering an application with django-oauth-toolkit, it looks a bit unpolished to me to display the hashed value in the form again on subsequent page loads, so I'm considering a second PR to only show the secret value once, when it is generated. But I want to make sure I support the HS256+OIDC flow as well in that PR.

Thanks!