Update install.rst
jazzband/django-oauth-toolkit pull request #852
Opened 2020-07-13 17:31 UTC by ericwood8

Added file location of `INSTALLED_APPS`

2020-09-15 13:51 UTC, n2ygk requested changes
Instead of referencing `settings.py` how about you link over to https://docs.djangoproject.com/en/dev/ref/settings/#installed-apps where it is documented? 

Note that I suggested the `dev` version since the only other versions of the documentation are pinned to a specific version number which will change over time.

2020-12-21 19:04 UTC, WoLpH approved these changes

2021-02-07 16:38 UTC, n2ygk approved these changes
Good enough.

2021-02-07 16:41 UTC, n2ygk commented
Going to have to close this since gh actions were added after this was submitted and they are blocking merging it.

2021-02-07 16:41 UTC, closed without merging