Gha smart run strategy
jazzband/django-oauth-toolkit pull request #937
Opened 2021-03-09 19:55 UTC by amureki

## Description of the Change

Previously, every pull request was running actions twice, since two signals were fired - push commit in the PR and new PR itself.

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [ ] unit-test added
- [ ] documentation updated
- [x] `CHANGELOG.md` updated (only for user relevant changes)
- [ ] author name in `AUTHORS`

2021-03-09 21:20 UTC, n2ygk requested changes

2021-03-09 21:20 UTC, n2ygk commented on CHANGELOG.md
> +### Fixed
Thanks for your contribution!

I don't believe this goes in the CHANGELOG though as it's not a user-visible change.

2021-03-09 21:21 UTC, n2ygk commented on CHANGELOG.md
> +### Fixed
Oh and please add yourself to AUTHORS

2021-03-10 00:25 UTC, merged

2021-03-10 10:50 UTC, jezdez commented
@amureki Please be so kind and revert this change, the use of both events is deliberate to account for all kinds of state changes a pull request can have, such as pushes happening to branches in forked repos that a pull request has been opneed against.

@n2ygk Please let me know if other pull requests come in about the GitHub Actions configuration so I can do a review. Thank you!

2021-03-10 11:19 UTC, amureki commented
@jezdez hey Jannis! I am sorry for bringing some confusion here. ATM trying to understand which states are not covered by this configuration.
I forked the repository and created a test PR here:
https://github.com/jazzband/django-oauth-toolkit/pull/938

![image](https://user-images.githubusercontent.com/627183/110621451-86b6b680-819a-11eb-88e7-946d1de0059f.png)


After seeing green actions build, I dropped another commit to see if it will retrigger actions event, and it did:
![image](https://user-images.githubusercontent.com/627183/110621513-97ffc300-819a-11eb-9526-f1cadf06017f.png)

I am creating a revert PR in any case, to not possibly block anyone.

2021-03-10 11:37 UTC, jezdez commented
> @jezdez hey Jannis! I am sorry for bringing some confusion here. ATM trying to understand which states are not covered by this configuration.
> I forked the repository and created a test PR here:
> #938
> 
> ![image](https://user-images.githubusercontent.com/627183/110621451-86b6b680-819a-11eb-88e7-946d1de0059f.png)
> 
> After seeing green actions build, I dropped another commit to see if it will retrigger actions event, and it did:
> ![image](https://user-images.githubusercontent.com/627183/110621513-97ffc300-819a-11eb-9526-f1cadf06017f.png)
> 
> I am creating a revert PR in any case, to not possibly block anyone.

Thanks for willing to dive into this, and you're right this seems to work. Sadly I don't have a working setup anymore where I was able to reproduce the edge cases with pull requests when I prepared the move from Travis to GitHub Actions. I appreciate your interest in figuring this out though!

IIRC it was a combination of pull requests being first being closed and reopened again and then not receiving push events anymore for changes in a fork branch. GitHub may have fixed it, or not, I can't really say without digging in again, their changelogs are not very detailed I'm afraid and last time the GitHub forum had a few people with similar issues. Personally I'm mostly concernd about consistency in running GitHub Actions for all Jazzband projects.

Thank you for resurfacing this since if it turns out to be not reproducable anymore I can update all the other Jazzband projects as well, which obviously would be a really nice thing to do, ecologically speaking. I'd appreciate a roll-back in the meantime though.

2021-03-10 11:50 UTC, amureki commented
@jezdez thank you for the detailed explanation! ✨ 

Whenever you have some time and will digging into this, feel free to drop me a line here or on `amureki @ hey.com` with some links to GitHub issues or forum topics that are related to the issue.
I'd be happy then to follow up on that and try to make some test sandbox to try to reproduce different use cases, so we can move forward and possibly optimize CI runs (also do to this across all Jazzband projects).